In [1]:
import os
import glob
import pandas as pd

In [2]:
# Used same code snippet for each season
# Downloaded monthly csv files, renamed it to data_year-month 
# Followed identical procedure for each subsequent season
# 2017-2018 season
all_files = glob.glob("data_*.csv")
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged_2017_2018   = pd.concat(df_from_each_file, ignore_index=True)
df_merged_2017_2018.to_csv("2017_2018_merged.csv")

In [3]:
df_merged_2017_2018

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 17, 2017",8:01p,Boston Celtics,99,Cleveland Cavaliers,102,Box Score,NaN,"20,562",NaN
1,"Tue, Oct 17, 2017",10:30p,Houston Rockets,122,Golden State Warriors,121,Box Score,NaN,"19,596",NaN
2,"Wed, Oct 18, 2017",7:00p,Charlotte Hornets,90,Detroit Pistons,102,Box Score,NaN,"20,491",NaN
3,"Wed, Oct 18, 2017",7:00p,Brooklyn Nets,131,Indiana Pacers,140,Box Score,NaN,"15,008",NaN
4,"Wed, Oct 18, 2017",7:00p,Miami Heat,109,Orlando Magic,116,Box Score,NaN,"18,846",NaN
...,...,...,...,...,...,...,...,...,...,...
1307,"Mon, May 28, 2018",9:00p,Golden State Warriors,101,Houston Rockets,92,Box Score,NaN,"18,055",NaN
1308,"Thu, May 31, 2018",9:00p,Cleveland Cavaliers,114,Golden State Warriors,124,Box Score,OT,"19,596",NaN
1309,"Sun, Jun 3, 2018",8:00p,Cleveland Cavaliers,103,Golden State Warriors,122,Box Score,NaN,"19,596",NaN
1310,"Wed, Jun 6, 2018",9:00p,Golden State Warriors,110,Cleveland Cavaliers,102,Box Score,NaN,"20,562",NaN
1311,"Fri, Jun 8, 2018",9:00p,Golden State Warriors,108,Cleveland Cavaliers,85,Box Score,NaN,"20,562",NaN

In [4]:
# 2018-2019 season
all_files = glob.glob("data_*.csv")
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged_2018_2019   = pd.concat(df_from_each_file, ignore_index=True)
df_merged_2018_2019.to_csv("2018_2019_merged.csv")

In [5]:
df_merged_2018_2019

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 16, 2018",8:00p,Philadelphia 76ers,87,Boston Celtics,105,Box Score,NaN,"18,624",NaN
1,"Tue, Oct 16, 2018",10:30p,Oklahoma City Thunder,100,Golden State Warriors,108,Box Score,NaN,"19,596",NaN
2,"Wed, Oct 17, 2018",7:00p,Milwaukee Bucks,113,Charlotte Hornets,112,Box Score,NaN,"17,889",NaN
3,"Wed, Oct 17, 2018",7:00p,Brooklyn Nets,100,Detroit Pistons,103,Box Score,NaN,"20,332",NaN
4,"Wed, Oct 17, 2018",7:00p,Memphis Grizzlies,83,Indiana Pacers,111,Box Score,NaN,"17,923",NaN
...,...,...,...,...,...,...,...,...,...,...
1307,"Sun, Jun 2, 2019",8:00p,Golden State Warriors,109,Toronto Raptors,104,Box Score,NaN,"20,014",NaN
1308,"Wed, Jun 5, 2019",9:00p,Toronto Raptors,123,Golden State Warriors,109,Box Score,NaN,"19,596",NaN
1309,"Fri, Jun 7, 2019",9:00p,Toronto Raptors,105,Golden State Warriors,92,Box Score,NaN,"19,596",NaN
1310,"Mon, Jun 10, 2019",9:00p,Golden State Warriors,106,Toronto Raptors,105,Box Score,NaN,"20,144",NaN
1311,"Thu, Jun 13, 2019",9:00p,Toronto Raptors,114,Golden State Warriors,110,Box Score,NaN,"19,596",NaN

In [6]:
# 2019-2020 season
all_files = glob.glob("data_*.csv")
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged_2019_2020   = pd.concat(df_from_each_file, ignore_index=True)
df_merged_2019_2020.to_csv("2019_2020_merged.csv")

In [7]:
df_merged_2019_2020

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 22, 2019",8:00p,New Orleans Pelicans,122,Toronto Raptors,130,Box Score,OT,"20,787",NaN
1,"Tue, Oct 22, 2019",10:30p,Los Angeles Lakers,102,Los Angeles Clippers,112,Box Score,NaN,"19,068",NaN
2,"Wed, Oct 23, 2019",7:00p,Chicago Bulls,125,Charlotte Hornets,126,Box Score,NaN,"15,424",NaN
3,"Wed, Oct 23, 2019",7:00p,Detroit Pistons,119,Indiana Pacers,110,Box Score,NaN,"17,923",NaN
4,"Wed, Oct 23, 2019",7:00p,Cleveland Cavaliers,85,Orlando Magic,94,Box Score,NaN,"18,846",NaN
...,...,...,...,...,...,...,...,...,...,...
1138,"Thu, Sep 24, 2020",9:00p,Los Angeles Lakers,114,Denver Nuggets,108,Box Score,NaN,NaN,NaN
1139,"Fri, Sep 25, 2020",8:30p,Miami Heat,108,Boston Celtics,121,Box Score,NaN,NaN,NaN
1140,"Sat, Sep 26, 2020",9:00p,Denver Nuggets,107,Los Angeles Lakers,117,Box Score,NaN,NaN,NaN
1141,"Sun, Sep 27, 2020",7:30p,Boston Celtics,113,Miami Heat,125,Box Score,NaN,NaN,NaN
1142,"Wed, Sep 30, 2020",9:00p,Miami Heat,98,Los Angeles Lakers,116,Box Score,NaN,NaN,NaN

In [8]:
# 2020-2021 season
all_files = glob.glob("data_*.csv")
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged_2020_2021   = pd.concat(df_from_each_file, ignore_index=True)
df_merged_2020_2021.to_csv("2020_2021_merged.csv")

In [9]:
df_merged_2020_2021

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Dec 22, 2020",7:00p,Golden State Warriors,99,Brooklyn Nets,125,Box Score,NaN,0,NaN
1,"Tue, Dec 22, 2020",10:00p,Los Angeles Clippers,116,Los Angeles Lakers,109,Box Score,NaN,0,NaN
2,"Wed, Dec 23, 2020",7:00p,Charlotte Hornets,114,Cleveland Cavaliers,121,Box Score,NaN,300,NaN
3,"Wed, Dec 23, 2020",7:00p,New York Knicks,107,Indiana Pacers,121,Box Score,NaN,0,NaN
4,"Wed, Dec 23, 2020",7:00p,Miami Heat,107,Orlando Magic,113,Box Score,NaN,"3,396",NaN
...,...,...,...,...,...,...,...,...,...,...
1166,"Thu, Jul 8, 2021",9:00p,Milwaukee Bucks,108,Phoenix Suns,118,Box Score,NaN,"16,583",NaN
1167,"Sun, Jul 11, 2021",8:00p,Phoenix Suns,100,Milwaukee Bucks,120,Box Score,NaN,"16,637",NaN
1168,"Wed, Jul 14, 2021",9:00p,Phoenix Suns,103,Milwaukee Bucks,109,Box Score,NaN,"16,911",NaN
1169,"Sat, Jul 17, 2021",9:00p,Milwaukee Bucks,123,Phoenix Suns,119,Box Score,NaN,"16,562",NaN
1170,"Tue, Jul 20, 2021",9:00p,Phoenix Suns,98,Milwaukee Bucks,105,Box Score,NaN,"17,397",NaN

In [10]:
# 2021-2022 season
all_files = glob.glob("data_*.csv")
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged_2021_2022   = pd.concat(df_from_each_file, ignore_index=True)
df_merged_2021_2022.to_csv("2021_2022_merged.csv")

In [11]:
df_merged_2021_2022

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 19, 2021",7:30p,Brooklyn Nets,104.0,Milwaukee Bucks,127.0,Box Score,NaN,"17,341",NaN
1,"Tue, Oct 19, 2021",10:00p,Golden State Warriors,121.0,Los Angeles Lakers,114.0,Box Score,NaN,"18,997",NaN
2,"Wed, Oct 20, 2021",7:00p,Indiana Pacers,122.0,Charlotte Hornets,123.0,Box Score,NaN,"15,521",NaN
3,"Wed, Oct 20, 2021",7:00p,Chicago Bulls,94.0,Detroit Pistons,88.0,Box Score,NaN,"20,088",NaN
4,"Wed, Oct 20, 2021",7:30p,Boston Celtics,134.0,New York Knicks,138.0,Box Score,2OT,"19,812",NaN
...,...,...,...,...,...,...,...,...,...,...
1225,"Sun, Apr 10, 2022",NaN,Los Angeles Lakers,NaN,Denver Nuggets,NaN,NaN,NaN,NaN,NaN
1226,"Sun, Apr 10, 2022",NaN,San Antonio Spurs,NaN,Dallas Mavericks,NaN,NaN,NaN,NaN,NaN
1227,"Sun, Apr 10, 2022",NaN,Milwaukee Bucks,NaN,Cleveland Cavaliers,NaN,NaN,NaN,NaN,NaN
1228,"Sun, Apr 10, 2022",NaN,Washington Wizards,NaN,Charlotte Hornets,NaN,NaN,NaN,NaN,NaN
1229,"Sun, Apr 10, 2022",NaN,Indiana Pacers,NaN,Brooklyn Nets,NaN,NaN,NaN,NaN,NaN